version: '7.0.2'

services:

    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${username}
            MONGO_INITDB_ROOT_PASSWORD: ${password}
        ports:
            - 27017:27017